version: '3.8'

services:
  discord-bot:
    build: .
    container_name: sniggering-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      # Mount the entire project directory to preserve file permissions
      - .:/app
    working_dir: /app
    # Uncomment if your bot serves HTTP endpoints
    # ports:
    #   - "3000:3000"